openapi: '3.0.2'
info:
  title: DHM (Data Harvester Microservice)
  version: 1.0.0
  description: |
    ## Overview

    The Data Havester Microservice (DHM) provides functionalities for retrieving streaming data.

    DHM offers the following RESTful HTTP method/s :

    | Operation                                   | Description |
    | ---                                         | --- |
    | **GET** /                                   | Get all data streamed from 3 platforms: Sytflix, Sytazon, Sysney


    ## Change History

    | Revision # | API Version # | Status      | Author            | Description                  | Date |
    | ---        | ---           | ---         | ---               | ---                          | ---  |
    | 1          | 1.0.0         | Draft       | Shiela MC         | Retrieve the streaming data  | 04-Sep-2023  |
    
  
  contact:
    name: Sytac
    email: info@sytac.io
    url: 'https://sytac.io/'

servers:
  - url: https://localhost:8080/dhm/v1
    description: pre-prod environments

tags:
- name: dhm
  description: Data Harvester Microservice (DHM) Methods

paths:
  /:
    get:
      operationId: collectDataFromStreams
      description: Get all the streaming data collected for 20 secs or 'til the 3rd occurrence of a
       firstname 'Sytac' on either of the streams. The 3 streaming platforms are Sytflix, Sytazon & Sysney.
      tags:
        - dhm
      summary: Get All Streaming Data
      responses:
        '200':
          description: List of collected data from streams.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_response_statistics'
        '500':
          $ref: '#/components/responses/500_error'
        '503':
          $ref: '#/components/responses/503_error'
  
components:
  schemas:
    eventData:
      type: object
      properties:
        eventId:
          type: string
          example: 734328e7-d574-4094-9d6b-d42da0a5e167
        eventName:
          type: string
          example: stream-interrupted
        showId:
          type: string
          example: "s41"
        cast:
          type: string
          example: "Kuby Farner"
        releaseYear:
          type: integer
          example: 2021
        title:
          type: string
          example: "Kancy Kancy (Dhorts)"
        platform:
          type: string
          example: "Sysney"
        eventDate:
          type: string
          example: "04-09-2023 07:43:22.196" 
    streamData:
      type: object
      properties:
        userId:
          type: string
          example: "44"
        completeName:
          type: string
          example: "Andras Boick"
        age:
          type: integer
          example: 41
        successfulEvents:
          type: integer
          example: 0
        eventList:
          type: array
          items:
            $ref: '#/components/schemas/eventData'
    stream_response_statistics:
      type: object
      properties:
        id:
          type: string
          example: 734328e7-d574-4094-9d6b-d42da0a5e167
        totalShowsReleasedIn2020AndLater:
          type: integer
          example: 74
        totalStreamingDurationMillis:
          type: integer
          example: 24130
        percentageStartedStreamingOnSytflix:
          type: number
          example: 21.50
        totalNumberOfEvents:
          type: integer
          example: 181
        streamingData:
          type: array
          items:
            $ref: '#/components/schemas/streamData'
          
    error_response_model:
      description: The error response model
      required:
        - status
        - error_code
        - description
      type: object
      properties:
        status:
          description: The HTTP status code
          type: string
        error_code:
          description: Code representing the error e.g. ERR_DHM_00000001
          type: string
        description:
          description: Description of the problem
          type: string
        error_sub_code:
          description: >-
            "More detailed or application level error code, may be used differentiate between
            variations of the main error type"
          type: string
        more_info:
          description: Further information regarding the error
          type: string
        doc_link:
          description: URL to documentation on the error e.g. suggestions for resolution
          type: string
  headers:
    X-Correlation-Id:
      schema:
        type: string
      description: Returns the correlation id generated by the API.
    Authorization:
      schema:
        type: string
      description: System Access Token
  responses:
    
    500_error:
      headers:
        X-Correlation-Id:
          schema:
            $ref: '#/components/headers/X-Correlation-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error_response_model'
          examples:
            'General Server Error':
              description: Unexpected error encountered on server. Contact admin for detail
              value:
                status: '500'
                error_code: ERR_DHM_00000500
                description: Internal server error
           
      description: SERVER ERROR - Internal Server Error
    503_error:
      headers:
        X-Correlation-Id:
          schema:
            $ref: '#/components/headers/X-Correlation-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error_response_model'
          examples:
            '503':
              value:
                status: '503'
                error_code: ERR_DHM_00000503
                description: Service unavailable
      description: SERVER ERROR - Service Unavailable